image: archlinux:latest

stages:
  - sign
  - deploy

sign_packages:
  stage: sign
  script:
    - echo "$GPG_PRIVATE_KEY" | gpg --import --batch
    - echo -e "5\ny\n" | gpg --command-fd 0 --edit-key $GPG_KEY_ID trust
    - mkdir -p ~/.gnupg
    - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
    - echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
    - cd rxrepo/os/x86_64/
    - for pkg in *.pkg.tar.zst; do
    -   echo "Signing $pkg..."
    -   gpg --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --detach-sign --use-agent -u "$GPG_KEY_ID" "$pkg"
    - done
    - chmod +x update_repo.sh
    - ./update_repo.sh
  artifacts:
    paths:
      - packages/

deploy_repo:
  stage: deploy
  image: archlinux:latest
  script:
    - ./update_repo.sh
  only:
    - main
