image: archlinux:latest

stages:
  - update

sign_packages:
  stage: update
  script:
    - pacman -Syu --noconfirm gnupg
    - mkdir -p ~/.gnupg
    - chmod 700 ~/.gnupg
    - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
    - echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
    - echo "no-tty" >> ~/.gnupg/gpg.conf
    - echo "batch" >> ~/.gnupg/gpg.conf
    - echo "yes" >> ~/.gnupg/gpg.conf
    - echo "$GPG_PRIVATE_KEY" | base64 -d | gpg --import --batch
    - echo -e "trust\n5\ny\nquit\n" | gpg --batch --command-fd 0 --no-tty --edit-key $GPG_KEY_ID
    - cd rxrepo/os/x86_64/
    - |
      for pkg in *.pkg.tar.zst; do
        echo "Checking for existing signature for $pkg..."
        if [ -f "$pkg.sig" ]; then
          echo "Removing existing signature file..."
          rm -f "$pkg.sig"
        fi
        echo "Signing $pkg..."
        gpg --batch --no-tty --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --detach-sign --use-agent -u "$GPG_KEY_ID" "$pkg"
      done
    - gpg --list-keys
    - cd ../../..
    - ls
    - repo-add --sign --key "$GPG_KEY_ID" -n -R ./rxrepo/os/x86_64/rxrepo.db.tar.gz ./rxrepo/os/x86_64/*.pkg.tar.zst
    - sleep 1
    - rm ./rxrepo/os/x86_64/rxrepo.db
    - rm ./rxrepo/os/x86_64/rxrepo.files
    - mv ./rxrepo/os/x86_64/rxrepo.db.tar.gz ./rxrepo/os/x86_64/rxrepo.db
    - mv ./rxrepo/os/x86_64/rxrepo.files.tar.gz ./rxrepo/os/x86_64/rxrepo.files
    - mv ./rxrepo/os/x86_64/rxrepo.db.tar.gz.sig ./rxrepo/os/x86_64/rxrepo.db.sig
    - mv ./rxrepo/os/x86_64/rxrepo.files.tar.gz.sig ./rxrepo/os/x86_64/rxrepo.files.sig
    - echo "####################################"
    - echo "Repo Updated!!"
    - echo "####################################"
    - mkdir -p public
    - cp -a rxrepo public/
  artifacts:
    paths:
      - public
  only:
    - main

pages:
  stage: update
  script:
    - echo "Deploying pages..."
  dependencies:
    - sign_packages
  artifacts:
    paths:
      - public
  only:
    - main
